server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /jeecg-boot
spring:
  #=====DataBase 相关===========
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lionherding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    druid:
      filters: stat,wall,log4j,config
      use-global-data-source-stat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  #=====Redis相关========
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 10
  #=====thymeleaf相关=========
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5
  #======静态资源相关 ===========
  resource:
    static-locations: classpath:/static/,classpath:/public/
  #=====日期格式相关=========
  #  mvc:
  #    date-format: yyyy-MM-dd

#=====Mybatis相关=====
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.lh.modules.*.entity,com.lh.system.entity
  configuration:
    map-underscore-to-camel-case: true  # 驼峰
  global-config:
    banner: false #关闭MP 3.0 自带的banner
#=====security相关======
#lh:
#  security:
#    browser:
#      loginPage: /demo-sign.html

#jeecg专用配置
jeecg :
  path :
    #文件上传根目录 设置
    upload: D://upFiles
    #webapp文件路径
    webapp: D://webapp
