#\u8DEF\u5F84\u540D
#server.servlet.context-path=/lh

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
#=====DataBase 相关===========
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lionherding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    druid:
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      use-global-data-source-stat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #=====Redis相关========
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 10

#=====日期格式相关=========
  mvc:
    date-format: yyyy-MM-dd

#=====Mybatis相关=====
mybatis-plus:
  mapper-locations: /mapper/**/*Mapper.xml
  type-aliases-package: com.lh.modules.model,com.lh.system.model

#=====日志相关=========
logging:
  level:
    com.lh: DEBUG

#
##===\u914D\u7F6Ethymeleaf\u76F8\u5173\u4FE1\u606F====
##\u7981\u7528\u7F13\u5B58
#spring.thymeleaf.cache=false
##\u914D\u7F6E\u6A21\u677F\u8DEF\u5F84
#spring.thymeleaf.prefix=classpath:/templates/
##\u68C0\u67E5\u6A21\u677F\u4F4D\u7F6E\u662F\u5426\u5B58\u5728
#spring.thymeleaf.check-template-location=true
##\u6307\u5B9A\u540E\u7F00
#spring.thymeleaf.suffix=.html
##\u7F16\u7801\u683C\u5F0F
#spring.thymeleaf.encoding=UTF-8
##\u5185\u5BB9\u7C7B\u522B
#spring.thymeleaf.servlet.content-type=text/html
##\u6A21\u677F\u7684\u6A21\u5F0F\uFF0C\u652F\u6301HTML\uFF0CXML\uFF0CTEXT JASASCRIPT
#spring.thymeleaf.mode=HTML5
##===\u914D\u7F6Ethymeleaf\u76F8\u5173\u4FE1\u606F====

