server:
  port: 8080
  servlet:
    session:
      timeout: 10
      uri-encoding: UTF-8

#=====DataBase 相关===========
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/lionherding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#      url: jdbc:mysql://192.168.0.217:3306/gbuy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 1
      min-idle: 1
      max-active: 5
      max-wait: 60000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    date-format: yyyy-MM-dd
#=====配置thymeleaf相关信息=====
#禁用缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5

#=====Redis相关========
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 10
#=====Mybatis相关=====
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.lh.system.model,com.lh.modules.model
  mapper-locations: classpath:mapper/system/*.xml

#=====日志相关=========
logging:
  level:
    com.lh: DEBUG

